# Generated by Django 5.1.1 on 2024-09-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshow', '0002_rename_comment_text_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_name',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
